[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "A5xNuD9bvbdEy97ViGAq2pNQBxNhaMgZNYWkxMa2mhDp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx --test --test-reporter=spec tests/*.ts"


